### ISSUE TITLE
Slack notifications about issues status

### ISSUE THREAD

**Issue by miquelegi** [systelab/seed-cpp#12]
**FINDINGS**
Currently no one receive any issues status. Every member of the seed or who are working in the issue should receive information when it is opened and changed.

**ACTION ITEMS AFTER FINDINGS**
Due to Slack is a CSW tool we can profit it to receive the issue status notifications. So then, every member of the seed, or the owner of the issue, QA and developer at least, shall receive information about every issue status:
- To Do
- In progress
- Done

**Comment by joaquimvila** [comment]
Configured slack channel **tf-cpp** to display changes about the status of this issue.
