### ISSUE TITLE
No matching member function for call to 'count'

### ISSUE THREAD

**Issue by alfonsserra** [systelab/seed-cpp#3]
In a Mac OS X environment, when making the application, the following error is thrown:

In file included from /Users/aserra/CppProjects/seed-cpp/extern/WebServerAdapter/WebServerAdapterInterface/Model/CORSConfiguration.h:59:
/Users/aserra/CppProjects/seed-cpp/extern/WebServerAdapter/WebServerAdapterInterface/Model/CORSConfiguration.inl:60:68: error: 
      no matching member function for call to 'count'
                return (m_allowedMethods.count(method) > 0) || (m_allowedMethods.count("*") > 0);
                                                                ~~~~~~~~~~~~~~~~~^~~~~

**Comment by joaquimvila** [comment]
Fixed on PR #4, which adds support for Mac OS X environment.
